--------------------------------------------------------
--  File created - Thursday-April-30-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AMONESTACION_REPARTIDOR
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."AMONESTACION_REPARTIDOR" 
   (	"AMONESTACION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"REPARTIDOR_ID" NUMBER, 
	"QUEJA_ID" NUMBER, 
	"ADMIN_USUARIO_ID" NUMBER, 
	"MOTIVO" VARCHAR2(300 BYTE), 
	"FECHA_AMONESTACION" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ACTIVA" CHAR(1 BYTE) DEFAULT 'S'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CALIFICACION_REPARTIDOR
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" 
   (	"CALIFICACION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PEDIDO_ID" NUMBER, 
	"REPARTIDOR_ID" NUMBER, 
	"CLIENTE_ID" NUMBER, 
	"PUNTAJE_AMABILIDAD" NUMBER(1,0), 
	"PUNTAJE_TIEMPO" NUMBER(1,0), 
	"PUNTAJE_PRESENTACION" NUMBER(1,0), 
	"COMENTARIO" VARCHAR2(300 BYTE), 
	"FECHA_CALIFICACION" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."CLIENTE" 
   (	"CLIENTE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USUARIO_ID" NUMBER, 
	"DIRECCION_EXACTA" VARCHAR2(250 BYTE), 
	"TARJETA_ULTIMOS4" VARCHAR2(4 BYTE), 
	"TOKEN_PAGO" VARCHAR2(150 BYTE), 
	"OBSERVACIONES" VARCHAR2(300 BYTE), 
	"CREADO_EN" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE_DIRECCION
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."CLIENTE_DIRECCION" 
   (	"DIRECCION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CLIENTE_ID" NUMBER, 
	"ALIAS" VARCHAR2(50 BYTE), 
	"DIRECCION_TEXTO" VARCHAR2(300 BYTE), 
	"LATITUD" NUMBER(10,7), 
	"LONGITUD" NUMBER(10,7), 
	"ES_PREDETERMINADA" CHAR(1 BYTE) DEFAULT 'N', 
	"ACTIVA" CHAR(1 BYTE) DEFAULT 'S', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMBO
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."COMBO" 
   (	"COMBO_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"RESTAURANTE_ID" NUMBER, 
	"NUMERO_COMBO" NUMBER(1,0), 
	"NOMBRE" VARCHAR2(80 BYTE), 
	"DESCRIPCION" VARCHAR2(250 BYTE), 
	"PRECIO" NUMBER(10,2), 
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'ACTIVO', 
	"IMAGEN_URL" VARCHAR2(255 BYTE), 
	"CREADO_EN" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACTURA
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."FACTURA" 
   (	"FACTURA_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PEDIDO_ID" NUMBER, 
	"NUMERO_FACTURA" VARCHAR2(30 BYTE), 
	"FECHA_EMISION" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"SUBTOTAL" NUMBER(12,2), 
	"COSTO_TRANSPORTE" NUMBER(12,2), 
	"PORCENTAJE_IVA" NUMBER(5,2) DEFAULT 13, 
	"MONTO_IVA" NUMBER(12,2), 
	"MONTO_TOTAL" NUMBER(12,2), 
	"ESTADO_PAGO" VARCHAR2(20 BYTE) DEFAULT 'PAGADO', 
	"MEDIO_PAGO" VARCHAR2(20 BYTE) DEFAULT 'TARJETA'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FERIADO
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."FERIADO" 
   (	"FERIADO_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FECHA" DATE, 
	"DESCRIPCION" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PEDIDO
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."PEDIDO" 
   (	"PEDIDO_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NUMERO_PEDIDO" VARCHAR2(30 BYTE), 
	"CLIENTE_ID" NUMBER, 
	"RESTAURANTE_ID" NUMBER, 
	"REPARTIDOR_ID" NUMBER, 
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'EN_PREPARACION', 
	"FECHA_PEDIDO" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"FECHA_ENTREGA" TIMESTAMP (6), 
	"DIRECCION_ENTREGA" VARCHAR2(250 BYTE), 
	"DISTANCIA_KM" NUMBER(10,2) DEFAULT 0, 
	"TIPO_TARIFA_DIA" CHAR(1 BYTE), 
	"COSTO_KM_APLICADO" NUMBER(10,2) DEFAULT 0, 
	"OBSERVACIONES" VARCHAR2(500 BYTE), 
	"CREADO_EN" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PEDIDO_DETALLE
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."PEDIDO_DETALLE" 
   (	"PEDIDO_DETALLE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PEDIDO_ID" NUMBER, 
	"COMBO_ID" NUMBER, 
	"CANTIDAD" NUMBER(5,0) DEFAULT 1, 
	"PRECIO_UNITARIO" NUMBER(10,2), 
	"SUBTOTAL_LINEA" NUMBER(12,2) GENERATED ALWAYS AS ("CANTIDAD"*"PRECIO_UNITARIO") VIRTUAL 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table QUEJA_REPARTIDOR
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."QUEJA_REPARTIDOR" 
   (	"QUEJA_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PEDIDO_ID" NUMBER, 
	"REPARTIDOR_ID" NUMBER, 
	"CLIENTE_ID" NUMBER, 
	"CATEGORIA" VARCHAR2(30 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'PENDIENTE', 
	"FECHA_QUEJA" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REPARTIDOR
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."REPARTIDOR" 
   (	"REPARTIDOR_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USUARIO_ID" NUMBER, 
	"DIRECCION_EXACTA" VARCHAR2(250 BYTE), 
	"TARJETA_ULTIMOS4" VARCHAR2(4 BYTE), 
	"TOKEN_PAGO" VARCHAR2(150 BYTE), 
	"DISPONIBILIDAD" VARCHAR2(20 BYTE) DEFAULT 'DISPONIBLE', 
	"KILOMETROS_RECORRIDOS_DIA" NUMBER(10,2) DEFAULT 0, 
	"COSTO_KM_HABIL" NUMBER(10,2) DEFAULT 1000, 
	"COSTO_KM_FERIADO" NUMBER(10,2) DEFAULT 1500, 
	"FECHA_INGRESO" DATE DEFAULT SYSDATE, 
	"FOTO_URL" VARCHAR2(255 BYTE), 
	"CREADO_EN" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESTAURANTE
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."RESTAURANTE" 
   (	"RESTAURANTE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(120 BYTE), 
	"CEDULA_JURIDICA" VARCHAR2(30 BYTE), 
	"DIRECCION" VARCHAR2(250 BYTE), 
	"TIPO_COMIDA" VARCHAR2(40 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'ACTIVO', 
	"IMAGEN_URL" VARCHAR2(255 BYTE), 
	"CREADO_EN" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"LATITUD" NUMBER(10,7), 
	"LONGITUD" NUMBER(10,7), 
	"UBICACION_ACTUALIZADA_EN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."ROL" 
   (	"ROL_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CODIGO" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "CLETAEATS"."USUARIO" 
   (	"USUARIO_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROL_ID" NUMBER, 
	"NOMBRE_COMPLETO" VARCHAR2(120 BYTE), 
	"CEDULA" VARCHAR2(20 BYTE), 
	"CORREO" VARCHAR2(120 BYTE), 
	"TELEFONO_CELULAR" VARCHAR2(20 BYTE), 
	"PASSWORD_HASH" VARCHAR2(255 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'ACTIVO', 
	"ULTIMO_LOGIN" TIMESTAMP (6), 
	"CREADO_EN" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View VW_REPARTIDOR_TOTAL_AMONESTACIONES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CLETAEATS"."VW_REPARTIDOR_TOTAL_AMONESTACIONES" ("REPARTIDOR_ID", "TOTAL_AMONESTACIONES") AS 
  SELECT
    r.repartidor_id,
    COUNT(CASE WHEN a.activa = 'S' THEN 1 END) AS total_amonestaciones
FROM repartidor r
LEFT JOIN amonestacion_repartidor a
       ON a.repartidor_id = r.repartidor_id
GROUP BY r.repartidor_id
;
--------------------------------------------------------
--  DDL for View VW_TOTAL_PEDIDOS_POR_CLIENTE
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CLETAEATS"."VW_TOTAL_PEDIDOS_POR_CLIENTE" ("CLIENTE_ID", "CLIENTE", "TOTAL_PEDIDOS") AS 
  SELECT
    c.cliente_id,
    u.nombre_completo AS cliente,
    COUNT(p.pedido_id) AS total_pedidos
FROM cliente c
JOIN usuario u
  ON u.usuario_id = c.usuario_id
LEFT JOIN pedido p
  ON p.cliente_id = c.cliente_id
GROUP BY c.cliente_id, u.nombre_completo
;
--------------------------------------------------------
--  DDL for View VW_TOTAL_VENDIDO_POR_RESTAURANTE
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CLETAEATS"."VW_TOTAL_VENDIDO_POR_RESTAURANTE" ("RESTAURANTE_ID", "RESTAURANTE", "TOTAL_VENDIDO", "TOTAL_PEDIDOS") AS 
  SELECT
    r.restaurante_id,
    r.nombre AS restaurante,
    NVL(SUM(f.monto_total), 0) AS total_vendido,
    COUNT(DISTINCT p.pedido_id) AS total_pedidos
FROM restaurante r
LEFT JOIN pedido p
       ON p.restaurante_id = r.restaurante_id
LEFT JOIN factura f
       ON f.pedido_id = p.pedido_id
GROUP BY r.restaurante_id, r.nombre
;
REM INSERTING into CLETAEATS.AMONESTACION_REPARTIDOR
SET DEFINE OFF;
Insert into CLETAEATS.AMONESTACION_REPARTIDOR (AMONESTACION_ID,REPARTIDOR_ID,QUEJA_ID,ADMIN_USUARIO_ID,MOTIVO,FECHA_AMONESTACION,ACTIVA) values (3,2,2,1,'Servicio',to_timestamp('24-APR-26 03.27.18.935945000 AM','DD-MON-RR HH.MI.SSXFF AM'),'S');
REM INSERTING into CLETAEATS.CALIFICACION_REPARTIDOR
SET DEFINE OFF;
Insert into CLETAEATS.CALIFICACION_REPARTIDOR (CALIFICACION_ID,PEDIDO_ID,REPARTIDOR_ID,CLIENTE_ID,PUNTAJE_AMABILIDAD,PUNTAJE_TIEMPO,PUNTAJE_PRESENTACION,COMENTARIO,FECHA_CALIFICACION) values (1,1,1,1,5,4,5,'Entrega rápida y buena atención',to_timestamp('23-APR-26 02.50.24.984000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.CALIFICACION_REPARTIDOR (CALIFICACION_ID,PEDIDO_ID,REPARTIDOR_ID,CLIENTE_ID,PUNTAJE_AMABILIDAD,PUNTAJE_TIEMPO,PUNTAJE_PRESENTACION,COMENTARIO,FECHA_CALIFICACION) values (2,2,2,2,4,4,4,'Buen servicio',to_timestamp('23-APR-26 02.50.24.994000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into CLETAEATS.CLIENTE
SET DEFINE OFF;
Insert into CLETAEATS.CLIENTE (CLIENTE_ID,USUARIO_ID,DIRECCION_EXACTA,TARJETA_ULTIMOS4,TOKEN_PAGO,OBSERVACIONES,CREADO_EN) values (4,7,'PENDIENTE',null,null,null,to_timestamp('24-APR-26 06.30.12.906000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.CLIENTE (CLIENTE_ID,USUARIO_ID,DIRECCION_EXACTA,TARJETA_ULTIMOS4,TOKEN_PAGO,OBSERVACIONES,CREADO_EN) values (3,6,'Escazu',null,null,null,to_timestamp('24-APR-26 01.50.15.235000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.CLIENTE (CLIENTE_ID,USUARIO_ID,DIRECCION_EXACTA,TARJETA_ULTIMOS4,TOKEN_PAGO,OBSERVACIONES,CREADO_EN) values (1,2,'Heredia Centro, del parque 200m norte, casa azul','1234','tok_cli_001','Cliente frecuente',to_timestamp('23-APR-26 02.50.24.757000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.CLIENTE (CLIENTE_ID,USUARIO_ID,DIRECCION_EXACTA,TARJETA_ULTIMOS4,TOKEN_PAGO,OBSERVACIONES,CREADO_EN) values (2,3,'San Francisco de Heredia, 100m oeste del súper','5678','tok_cli_002','Sin observaciones',to_timestamp('23-APR-26 02.50.24.765000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into CLETAEATS.CLIENTE_DIRECCION
SET DEFINE OFF;
Insert into CLETAEATS.CLIENTE_DIRECCION (DIRECCION_ID,CLIENTE_ID,ALIAS,DIRECCION_TEXTO,LATITUD,LONGITUD,ES_PREDETERMINADA,ACTIVA,CREATED_AT,UPDATED_AT) values (1,3,'Casa','WV37+8Q6, San José Province, San Antonio, Costa Rica',9.9034683,-84.1361714,'N','N',to_timestamp('25-APR-26 02.37.07.024580000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('26-APR-26 04.47.14.081206000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.CLIENTE_DIRECCION (DIRECCION_ID,CLIENTE_ID,ALIAS,DIRECCION_TEXTO,LATITUD,LONGITUD,ES_PREDETERMINADA,ACTIVA,CREATED_AT,UPDATED_AT) values (24,3,'Trabajo','100 mts Este100 mts Sur de Plaza San Jose Hospital, San José Province, San José, Bolivar, 10103, Costa Rica',9.9270369,-84.0947869,'N','S',to_timestamp('26-APR-26 05.03.38.437264000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('26-APR-26 05.08.39.082056000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.CLIENTE_DIRECCION (DIRECCION_ID,CLIENTE_ID,ALIAS,DIRECCION_TEXTO,LATITUD,LONGITUD,ES_PREDETERMINADA,ACTIVA,CREATED_AT,UPDATED_AT) values (21,3,'Trabajo','Mata Redonda, Gimnasio Nacional Eddy Cortes, oficina #1, San José, Sabana, 10108, Costa Rica',9.9326089,-84.0985471,'N','N',to_timestamp('26-APR-26 04.44.26.293428000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('26-APR-26 04.47.15.465794000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.CLIENTE_DIRECCION (DIRECCION_ID,CLIENTE_ID,ALIAS,DIRECCION_TEXTO,LATITUD,LONGITUD,ES_PREDETERMINADA,ACTIVA,CREATED_AT,UPDATED_AT) values (22,3,'Casa','WV37+8Q6, San José Province, San Antonio, Costa Rica',9.9033794,-84.1360259,'S','S',to_timestamp('26-APR-26 04.47.45.997902000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('26-APR-26 05.08.39.082056000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.CLIENTE_DIRECCION (DIRECCION_ID,CLIENTE_ID,ALIAS,DIRECCION_TEXTO,LATITUD,LONGITUD,ES_PREDETERMINADA,ACTIVA,CREATED_AT,UPDATED_AT) values (23,3,'Trabajo','Av. 20 calle 1820, San José, Sabana Sur, 10303, Costa Rica',9.9323513,-84.0983509,'N','N',to_timestamp('26-APR-26 04.48.01.646685000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('26-APR-26 05.03.30.027990000 PM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into CLETAEATS.COMBO
SET DEFINE OFF;
Insert into CLETAEATS.COMBO (COMBO_ID,RESTAURANTE_ID,NUMERO_COMBO,NOMBRE,DESCRIPCION,PRECIO,ESTADO,IMAGEN_URL,CREADO_EN,ACTUALIZADO_EN) values (1,1,1,'Combo Clásico','Hamburguesa, papas y bebida',4000,'ACTIVO','https://picsum.photos/300?21',to_timestamp('23-APR-26 02.50.24.832000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 02.50.24.832000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.COMBO (COMBO_ID,RESTAURANTE_ID,NUMERO_COMBO,NOMBRE,DESCRIPCION,PRECIO,ESTADO,IMAGEN_URL,CREADO_EN,ACTUALIZADO_EN) values (2,1,2,'Combo Doble','Hamburguesa doble, papas grandes y bebida',5000,'ACTIVO','https://picsum.photos/300?22',to_timestamp('23-APR-26 02.50.24.839000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 02.50.24.839000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.COMBO (COMBO_ID,RESTAURANTE_ID,NUMERO_COMBO,NOMBRE,DESCRIPCION,PRECIO,ESTADO,IMAGEN_URL,CREADO_EN,ACTUALIZADO_EN) values (3,2,1,'Combo Arroz','Arroz cantonés con bebida',4000,'ACTIVO','https://picsum.photos/300?23',to_timestamp('23-APR-26 02.50.24.849000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 02.50.24.849000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.COMBO (COMBO_ID,RESTAURANTE_ID,NUMERO_COMBO,NOMBRE,DESCRIPCION,PRECIO,ESTADO,IMAGEN_URL,CREADO_EN,ACTUALIZADO_EN) values (4,2,2,'Combo Chop Suey','Chop suey con arroz y bebida',5000,'ACTIVO','https://picsum.photos/300?24',to_timestamp('23-APR-26 02.50.24.856000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 02.50.24.856000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into CLETAEATS.FACTURA
SET DEFINE OFF;
Insert into CLETAEATS.FACTURA (FACTURA_ID,PEDIDO_ID,NUMERO_FACTURA,FECHA_EMISION,SUBTOTAL,COSTO_TRANSPORTE,PORCENTAJE_IVA,MONTO_IVA,MONTO_TOTAL,ESTADO_PAGO,MEDIO_PAGO) values (1,1,'FAC-0001',to_timestamp('23-APR-26 02.50.24.961000000 PM','DD-MON-RR HH.MI.SSXFF AM'),8000,3500,13,1495,12995,'PAGADO','TARJETA');
Insert into CLETAEATS.FACTURA (FACTURA_ID,PEDIDO_ID,NUMERO_FACTURA,FECHA_EMISION,SUBTOTAL,COSTO_TRANSPORTE,PORCENTAJE_IVA,MONTO_IVA,MONTO_TOTAL,ESTADO_PAGO,MEDIO_PAGO) values (2,2,'FAC-0002',to_timestamp('23-APR-26 02.50.24.968000000 PM','DD-MON-RR HH.MI.SSXFF AM'),5000,5000,13,1300,11300,'PAGADO','TARJETA');
Insert into CLETAEATS.FACTURA (FACTURA_ID,PEDIDO_ID,NUMERO_FACTURA,FECHA_EMISION,SUBTOTAL,COSTO_TRANSPORTE,PORCENTAJE_IVA,MONTO_IVA,MONTO_TOTAL,ESTADO_PAGO,MEDIO_PAGO) values (3,19,'FAC-REP-001',to_timestamp('24-APR-26 11.56.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),13000,3200,13,2106,18306,'PAGADO','TARJETA');
Insert into CLETAEATS.FACTURA (FACTURA_ID,PEDIDO_ID,NUMERO_FACTURA,FECHA_EMISION,SUBTOTAL,COSTO_TRANSPORTE,PORCENTAJE_IVA,MONTO_IVA,MONTO_TOTAL,ESTADO_PAGO,MEDIO_PAGO) values (4,20,'FAC-REP-002',to_timestamp('24-APR-26 12.21.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),6000,2500,13,1105,9605,'PENDIENTE','EFECTIVO');
Insert into CLETAEATS.FACTURA (FACTURA_ID,PEDIDO_ID,NUMERO_FACTURA,FECHA_EMISION,SUBTOTAL,COSTO_TRANSPORTE,PORCENTAJE_IVA,MONTO_IVA,MONTO_TOTAL,ESTADO_PAGO,MEDIO_PAGO) values (5,21,'FAC-REP-003',to_timestamp('24-APR-26 01.36.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),4000,1800,13,754,6554,'PAGADO','SINPE');
Insert into CLETAEATS.FACTURA (FACTURA_ID,PEDIDO_ID,NUMERO_FACTURA,FECHA_EMISION,SUBTOTAL,COSTO_TRANSPORTE,PORCENTAJE_IVA,MONTO_IVA,MONTO_TOTAL,ESTADO_PAGO,MEDIO_PAGO) values (6,22,'FAC-REP-004',to_timestamp('24-APR-26 02.11.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),7000,4100,13,1443,12543,'PENDIENTE','TARJETA');
REM INSERTING into CLETAEATS.FERIADO
SET DEFINE OFF;
REM INSERTING into CLETAEATS.PEDIDO
SET DEFINE OFF;
Insert into CLETAEATS.PEDIDO (PEDIDO_ID,NUMERO_PEDIDO,CLIENTE_ID,RESTAURANTE_ID,REPARTIDOR_ID,ESTADO,FECHA_PEDIDO,FECHA_ENTREGA,DIRECCION_ENTREGA,DISTANCIA_KM,TIPO_TARIFA_DIA,COSTO_KM_APLICADO,OBSERVACIONES,CREADO_EN,ACTUALIZADO_EN) values (1,'PED-0001',1,1,1,'ENTREGADO',to_timestamp('23-APR-26 11.50.24.885000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 12.50.24.885000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Heredia Centro, del parque 200m norte, casa azul',3.5,'H',1000,'Sin cebolla',to_timestamp('23-APR-26 02.50.24.885000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 02.50.24.885000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.PEDIDO (PEDIDO_ID,NUMERO_PEDIDO,CLIENTE_ID,RESTAURANTE_ID,REPARTIDOR_ID,ESTADO,FECHA_PEDIDO,FECHA_ENTREGA,DIRECCION_ENTREGA,DISTANCIA_KM,TIPO_TARIFA_DIA,COSTO_KM_APLICADO,OBSERVACIONES,CREADO_EN,ACTUALIZADO_EN) values (2,'PED-0002',2,2,2,'EN_CAMINO',to_timestamp('23-APR-26 01.50.24.900000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,'San Francisco de Heredia, 100m oeste del súper',5,'H',1000,'Tocar el timbre',to_timestamp('23-APR-26 02.50.24.900000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 02.50.24.900000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.PEDIDO (PEDIDO_ID,NUMERO_PEDIDO,CLIENTE_ID,RESTAURANTE_ID,REPARTIDOR_ID,ESTADO,FECHA_PEDIDO,FECHA_ENTREGA,DIRECCION_ENTREGA,DISTANCIA_KM,TIPO_TARIFA_DIA,COSTO_KM_APLICADO,OBSERVACIONES,CREADO_EN,ACTUALIZADO_EN) values (19,'PED-REP-001',1,2,1,'ENTREGADO',to_timestamp('24-APR-26 11.15.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('24-APR-26 11.55.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Dirección prueba 1',3.2,'H',1000,'Pedido de prueba para reportes',to_timestamp('24-APR-26 03.52.42.914000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('24-APR-26 03.52.42.914000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.PEDIDO (PEDIDO_ID,NUMERO_PEDIDO,CLIENTE_ID,RESTAURANTE_ID,REPARTIDOR_ID,ESTADO,FECHA_PEDIDO,FECHA_ENTREGA,DIRECCION_ENTREGA,DISTANCIA_KM,TIPO_TARIFA_DIA,COSTO_KM_APLICADO,OBSERVACIONES,CREADO_EN,ACTUALIZADO_EN) values (20,'PED-REP-002',1,2,1,'EN_CAMINO',to_timestamp('24-APR-26 12.20.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,'Dirección prueba 2',2.5,'H',1000,'Pedido de prueba para reportes',to_timestamp('24-APR-26 03.52.42.987000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('24-APR-26 03.52.42.987000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.PEDIDO (PEDIDO_ID,NUMERO_PEDIDO,CLIENTE_ID,RESTAURANTE_ID,REPARTIDOR_ID,ESTADO,FECHA_PEDIDO,FECHA_ENTREGA,DIRECCION_ENTREGA,DISTANCIA_KM,TIPO_TARIFA_DIA,COSTO_KM_APLICADO,OBSERVACIONES,CREADO_EN,ACTUALIZADO_EN) values (21,'PED-REP-003',2,3,2,'ENTREGADO',to_timestamp('24-APR-26 01.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('24-APR-26 01.35.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Dirección prueba 3',1.8,'H',1000,'Pedido de prueba para reportes',to_timestamp('24-APR-26 03.52.43.040000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('24-APR-26 03.52.43.040000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.PEDIDO (PEDIDO_ID,NUMERO_PEDIDO,CLIENTE_ID,RESTAURANTE_ID,REPARTIDOR_ID,ESTADO,FECHA_PEDIDO,FECHA_ENTREGA,DIRECCION_ENTREGA,DISTANCIA_KM,TIPO_TARIFA_DIA,COSTO_KM_APLICADO,OBSERVACIONES,CREADO_EN,ACTUALIZADO_EN) values (22,'PED-REP-004',1,2,1,'EN_PREPARACION',to_timestamp('24-APR-26 02.10.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,'Dirección prueba 4',4.1,'H',1000,'Pedido de prueba para reportes',to_timestamp('24-APR-26 03.52.43.103000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('24-APR-26 03.52.43.103000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into CLETAEATS.PEDIDO_DETALLE
SET DEFINE OFF;
Insert into CLETAEATS.PEDIDO_DETALLE (PEDIDO_DETALLE_ID,PEDIDO_ID,COMBO_ID,CANTIDAD,PRECIO_UNITARIO,SUBTOTAL_LINEA) values (1,1,1,2,4000,8000);
Insert into CLETAEATS.PEDIDO_DETALLE (PEDIDO_DETALLE_ID,PEDIDO_ID,COMBO_ID,CANTIDAD,PRECIO_UNITARIO,SUBTOTAL_LINEA) values (2,2,4,1,5000,5000);
Insert into CLETAEATS.PEDIDO_DETALLE (PEDIDO_DETALLE_ID,PEDIDO_ID,COMBO_ID,CANTIDAD,PRECIO_UNITARIO,SUBTOTAL_LINEA) values (3,19,3,2,4000,8000);
Insert into CLETAEATS.PEDIDO_DETALLE (PEDIDO_DETALLE_ID,PEDIDO_ID,COMBO_ID,CANTIDAD,PRECIO_UNITARIO,SUBTOTAL_LINEA) values (4,19,4,1,5000,5000);
REM INSERTING into CLETAEATS.QUEJA_REPARTIDOR
SET DEFINE OFF;
Insert into CLETAEATS.QUEJA_REPARTIDOR (QUEJA_ID,PEDIDO_ID,REPARTIDOR_ID,CLIENTE_ID,CATEGORIA,DESCRIPCION,ESTADO,FECHA_QUEJA) values (1,1,1,1,'TIEMPO','La entrega tardó más de lo esperado','EN_REVISION',to_timestamp('23-APR-26 02.50.25.012000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.QUEJA_REPARTIDOR (QUEJA_ID,PEDIDO_ID,REPARTIDOR_ID,CLIENTE_ID,CATEGORIA,DESCRIPCION,ESTADO,FECHA_QUEJA) values (2,2,2,2,'SERVICIO','El pedido llegó con poca claridad en la entrega','RESUELTA',to_timestamp('23-APR-26 02.50.25.019000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into CLETAEATS.REPARTIDOR
SET DEFINE OFF;
Insert into CLETAEATS.REPARTIDOR (REPARTIDOR_ID,USUARIO_ID,DIRECCION_EXACTA,TARJETA_ULTIMOS4,TOKEN_PAGO,DISPONIBILIDAD,KILOMETROS_RECORRIDOS_DIA,COSTO_KM_HABIL,COSTO_KM_FERIADO,FECHA_INGRESO,FOTO_URL,CREADO_EN) values (21,8,'PENDIENTE',null,null,'DISPONIBLE',0,1000,1500,to_date('24-APR-26','DD-MON-RR'),null,to_timestamp('24-APR-26 06.48.35.712000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.REPARTIDOR (REPARTIDOR_ID,USUARIO_ID,DIRECCION_EXACTA,TARJETA_ULTIMOS4,TOKEN_PAGO,DISPONIBILIDAD,KILOMETROS_RECORRIDOS_DIA,COSTO_KM_HABIL,COSTO_KM_FERIADO,FECHA_INGRESO,FOTO_URL,CREADO_EN) values (1,4,'Mercedes Norte, 50m sur de la plaza','1111','tok_rep_001','DISPONIBLE',12.5,1000,1500,to_date('23-APR-26','DD-MON-RR'),'https://picsum.photos/200?1',to_timestamp('23-APR-26 02.50.24.779000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.REPARTIDOR (REPARTIDOR_ID,USUARIO_ID,DIRECCION_EXACTA,TARJETA_ULTIMOS4,TOKEN_PAGO,DISPONIBILIDAD,KILOMETROS_RECORRIDOS_DIA,COSTO_KM_HABIL,COSTO_KM_FERIADO,FECHA_INGRESO,FOTO_URL,CREADO_EN) values (2,5,'Ulloa, 300m este de la iglesia','2222','tok_rep_002','OCUPADO',8,1000,1500,to_date('23-APR-26','DD-MON-RR'),'https://picsum.photos/200?2',to_timestamp('23-APR-26 02.50.24.785000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into CLETAEATS.RESTAURANTE
SET DEFINE OFF;
Insert into CLETAEATS.RESTAURANTE (RESTAURANTE_ID,NOMBRE,CEDULA_JURIDICA,DIRECCION,TIPO_COMIDA,ESTADO,IMAGEN_URL,CREADO_EN,ACTUALIZADO_EN,LATITUD,LONGITUD,UBICACION_ACTUALIZADA_EN) values (3,'Green Bowl','3-101-000003','Heredia, cerca del parque central','SALUDABLE','ACTIVO','https://picsum.photos/400?33',to_timestamp('23-APR-26 03.40.14.724000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 03.40.14.724000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into CLETAEATS.RESTAURANTE (RESTAURANTE_ID,NOMBRE,CEDULA_JURIDICA,DIRECCION,TIPO_COMIDA,ESTADO,IMAGEN_URL,CREADO_EN,ACTUALIZADO_EN,LATITUD,LONGITUD,UBICACION_ACTUALIZADA_EN) values (1,'Burger Point Plus','3-101-000001','Heredia Centro, avenida 2 remodelado','RAPIDA','INACTIVO','https://picsum.photos/400?34',to_timestamp('23-APR-26 02.50.24.799000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 02.50.24.799000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
Insert into CLETAEATS.RESTAURANTE (RESTAURANTE_ID,NOMBRE,CEDULA_JURIDICA,DIRECCION,TIPO_COMIDA,ESTADO,IMAGEN_URL,CREADO_EN,ACTUALIZADO_EN,LATITUD,LONGITUD,UBICACION_ACTUALIZADA_EN) values (2,'Wok Express','3-101-000002','San Pablo de Heredia, calle principal','CHINA','ACTIVO','https://picsum.photos/400?11',to_timestamp('23-APR-26 02.50.24.805000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 02.50.24.805000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null);
REM INSERTING into CLETAEATS.ROL
SET DEFINE OFF;
Insert into CLETAEATS.ROL (ROL_ID,CODIGO,NOMBRE,DESCRIPCION) values (1,'ADMIN','Administrador','Usuario de administración web');
Insert into CLETAEATS.ROL (ROL_ID,CODIGO,NOMBRE,DESCRIPCION) values (2,'CLIENTE','Cliente','Usuario móvil que realiza pedidos');
Insert into CLETAEATS.ROL (ROL_ID,CODIGO,NOMBRE,DESCRIPCION) values (3,'REPARTIDOR','Repartidor','Usuario móvil que entrega pedidos');
REM INSERTING into CLETAEATS.USUARIO
SET DEFINE OFF;
Insert into CLETAEATS.USUARIO (USUARIO_ID,ROL_ID,NOMBRE_COMPLETO,CEDULA,CORREO,TELEFONO_CELULAR,PASSWORD_HASH,ESTADO,ULTIMO_LOGIN,CREADO_EN,ACTUALIZADO_EN) values (7,2,'Alejandro Alvarez','118910804','alealcha123@gmail.com','88085341','$2a$10$4D8TmOiYjTCK4T6/nWAeHeaP/7ohnVCYkBK6Xim1T/DQsa1eP/4h2','ACTIVO',null,to_timestamp('24-APR-26 06.30.12.824000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('24-APR-26 06.30.12.824000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.USUARIO (USUARIO_ID,ROL_ID,NOMBRE_COMPLETO,CEDULA,CORREO,TELEFONO_CELULAR,PASSWORD_HASH,ESTADO,ULTIMO_LOGIN,CREADO_EN,ACTUALIZADO_EN) values (8,3,'Manita','117910804','manita@cletaeats.com','83551117','$2a$10$nMdNdA8jmPbpQFtbh6PEIe5VF/FZ0T9omb2nyKqBwcG/6QtUNz6uS','ACTIVO',null,to_timestamp('24-APR-26 06.48.35.565000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('24-APR-26 06.48.35.565000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.USUARIO (USUARIO_ID,ROL_ID,NOMBRE_COMPLETO,CEDULA,CORREO,TELEFONO_CELULAR,PASSWORD_HASH,ESTADO,ULTIMO_LOGIN,CREADO_EN,ACTUALIZADO_EN) values (6,2,'Max Alvarez','901250207','max@cletaeats.com','88088808','$2a$10$cAm2N8ZxHyxijE//lu.pwuTtdfxiHhThqt3NgVuiAp/akua7PflqS','ACTIVO',null,to_timestamp('24-APR-26 01.50.15.209000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('24-APR-26 01.50.15.209000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.USUARIO (USUARIO_ID,ROL_ID,NOMBRE_COMPLETO,CEDULA,CORREO,TELEFONO_CELULAR,PASSWORD_HASH,ESTADO,ULTIMO_LOGIN,CREADO_EN,ACTUALIZADO_EN) values (1,1,'Admin CletaEats','109990001','admin@cletaeats.com','88880001','admin123','ACTIVO',null,to_timestamp('23-APR-26 02.50.24.707000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 02.50.24.707000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.USUARIO (USUARIO_ID,ROL_ID,NOMBRE_COMPLETO,CEDULA,CORREO,TELEFONO_CELULAR,PASSWORD_HASH,ESTADO,ULTIMO_LOGIN,CREADO_EN,ACTUALIZADO_EN) values (2,2,'María Fernández','109990002','maria@correo.com','88880002','cliente123','ACTIVO',null,to_timestamp('23-APR-26 02.50.24.720000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 02.50.24.720000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.USUARIO (USUARIO_ID,ROL_ID,NOMBRE_COMPLETO,CEDULA,CORREO,TELEFONO_CELULAR,PASSWORD_HASH,ESTADO,ULTIMO_LOGIN,CREADO_EN,ACTUALIZADO_EN) values (3,2,'Carlos Rodríguez','109990003','carlos@correo.com','88880003','cliente123','ACTIVO',null,to_timestamp('23-APR-26 02.50.24.727000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 02.50.24.727000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.USUARIO (USUARIO_ID,ROL_ID,NOMBRE_COMPLETO,CEDULA,CORREO,TELEFONO_CELULAR,PASSWORD_HASH,ESTADO,ULTIMO_LOGIN,CREADO_EN,ACTUALIZADO_EN) values (4,3,'Luis Herrera','109990004','luis@correo.com','88880004','repartidor123','ACTIVO',null,to_timestamp('23-APR-26 02.50.24.737000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 02.50.24.737000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CLETAEATS.USUARIO (USUARIO_ID,ROL_ID,NOMBRE_COMPLETO,CEDULA,CORREO,TELEFONO_CELULAR,PASSWORD_HASH,ESTADO,ULTIMO_LOGIN,CREADO_EN,ACTUALIZADO_EN) values (5,3,'Sofía Morales','109990005','sofia@correo.com','88880005','repartidor123','ACTIVO',null,to_timestamp('23-APR-26 02.50.24.742000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('23-APR-26 02.50.24.742000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
--------------------------------------------------------
--  DDL for Index UQ_COMBO_NUMERO_POR_REST
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLETAEATS"."UQ_COMBO_NUMERO_POR_REST" ON "CLETAEATS"."COMBO" ("RESTAURANTE_ID", "NUMERO_COMBO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PEDIDO_ESTADO
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_PEDIDO_ESTADO" ON "CLETAEATS"."PEDIDO" ("ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_QUEJA_REPARTIDOR
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_QUEJA_REPARTIDOR" ON "CLETAEATS"."QUEJA_REPARTIDOR" ("REPARTIDOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_FERIADO_FECHA
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLETAEATS"."UQ_FERIADO_FECHA" ON "CLETAEATS"."FERIADO" ("FECHA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_PEDIDO_NUMERO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLETAEATS"."UQ_PEDIDO_NUMERO" ON "CLETAEATS"."PEDIDO" ("NUMERO_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_FACTURA_PEDIDO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLETAEATS"."UQ_FACTURA_PEDIDO" ON "CLETAEATS"."FACTURA" ("PEDIDO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_REST_CED_JURIDICA
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLETAEATS"."UQ_REST_CED_JURIDICA" ON "CLETAEATS"."RESTAURANTE" ("CEDULA_JURIDICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_CALIF_PEDIDO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLETAEATS"."UQ_CALIF_PEDIDO" ON "CLETAEATS"."CALIFICACION_REPARTIDOR" ("PEDIDO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PEDIDO_CLIENTE
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_PEDIDO_CLIENTE" ON "CLETAEATS"."PEDIDO" ("CLIENTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_AMONESTACION_REPARTIDOR
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_AMONESTACION_REPARTIDOR" ON "CLETAEATS"."AMONESTACION_REPARTIDOR" ("REPARTIDOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_USUARIO_CEDULA
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLETAEATS"."UQ_USUARIO_CEDULA" ON "CLETAEATS"."USUARIO" ("CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_FACTURA_NUMERO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLETAEATS"."UQ_FACTURA_NUMERO" ON "CLETAEATS"."FACTURA" ("NUMERO_FACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_USUARIO_ROL
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_USUARIO_ROL" ON "CLETAEATS"."USUARIO" ("ROL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_USUARIO_ESTADO
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_USUARIO_ESTADO" ON "CLETAEATS"."USUARIO" ("ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_CLIENTE_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLETAEATS"."UQ_CLIENTE_USUARIO" ON "CLETAEATS"."CLIENTE" ("USUARIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_CLIENTE_DIRECCION_CLIENTE
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_CLIENTE_DIRECCION_CLIENTE" ON "CLETAEATS"."CLIENTE_DIRECCION" ("CLIENTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_COMBO_RESTAURANTE
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_COMBO_RESTAURANTE" ON "CLETAEATS"."COMBO" ("RESTAURANTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_COMBO_ESTADO
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_COMBO_ESTADO" ON "CLETAEATS"."COMBO" ("ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_ROL_CODIGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLETAEATS"."UQ_ROL_CODIGO" ON "CLETAEATS"."ROL" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PEDIDO_RESTAURANTE
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_PEDIDO_RESTAURANTE" ON "CLETAEATS"."PEDIDO" ("RESTAURANTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_REPARTIDOR_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLETAEATS"."UQ_REPARTIDOR_USUARIO" ON "CLETAEATS"."REPARTIDOR" ("USUARIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PEDIDO_FECHA
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_PEDIDO_FECHA" ON "CLETAEATS"."PEDIDO" ("FECHA_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_USUARIO_CORREO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLETAEATS"."UQ_USUARIO_CORREO" ON "CLETAEATS"."USUARIO" ("CORREO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_RESTAURANTE_GEO
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_RESTAURANTE_GEO" ON "CLETAEATS"."RESTAURANTE" ("LATITUD", "LONGITUD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PEDIDO_REPARTIDOR
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_PEDIDO_REPARTIDOR" ON "CLETAEATS"."PEDIDO" ("REPARTIDOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_RESTAURANTE_ESTADO
--------------------------------------------------------

  CREATE INDEX "CLETAEATS"."IDX_RESTAURANTE_ESTADO" ON "CLETAEATS"."RESTAURANTE" ("ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RESTAURANTE
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."RESTAURANTE" MODIFY ("RESTAURANTE_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."RESTAURANTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."RESTAURANTE" MODIFY ("CEDULA_JURIDICA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."RESTAURANTE" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."RESTAURANTE" MODIFY ("TIPO_COMIDA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."RESTAURANTE" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."RESTAURANTE" MODIFY ("CREADO_EN" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."RESTAURANTE" MODIFY ("ACTUALIZADO_EN" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."RESTAURANTE" ADD CONSTRAINT "CK_REST_ESTADO" CHECK (estado IN ('ACTIVO', 'INACTIVO')) ENABLE;
  ALTER TABLE "CLETAEATS"."RESTAURANTE" ADD PRIMARY KEY ("RESTAURANTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."RESTAURANTE" ADD CONSTRAINT "UQ_REST_CED_JURIDICA" UNIQUE ("CEDULA_JURIDICA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."RESTAURANTE" ADD CONSTRAINT "CK_REST_LATITUD" CHECK (latitud IS NULL OR (latitud BETWEEN -90 AND 90)) ENABLE;
  ALTER TABLE "CLETAEATS"."RESTAURANTE" ADD CONSTRAINT "CK_REST_LONGITUD" CHECK (longitud IS NULL OR (longitud BETWEEN -180 AND 180)) ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."FACTURA" MODIFY ("FACTURA_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FACTURA" MODIFY ("PEDIDO_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FACTURA" MODIFY ("NUMERO_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FACTURA" MODIFY ("FECHA_EMISION" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FACTURA" MODIFY ("SUBTOTAL" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FACTURA" MODIFY ("COSTO_TRANSPORTE" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FACTURA" MODIFY ("PORCENTAJE_IVA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FACTURA" MODIFY ("MONTO_IVA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FACTURA" MODIFY ("MONTO_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FACTURA" MODIFY ("ESTADO_PAGO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FACTURA" MODIFY ("MEDIO_PAGO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FACTURA" ADD CONSTRAINT "CK_FACTURA_ESTADO" CHECK (estado_pago IN ('PAGADO', 'PENDIENTE', 'REVERTIDO')) ENABLE;
  ALTER TABLE "CLETAEATS"."FACTURA" ADD CONSTRAINT "CK_FACTURA_VALORES" CHECK (
        subtotal >= 0 AND
        costo_transporte >= 0 AND
        porcentaje_iva >= 0 AND
        monto_iva >= 0 AND
        monto_total = ROUND(subtotal + costo_transporte + monto_iva, 2)
    ) ENABLE;
  ALTER TABLE "CLETAEATS"."FACTURA" ADD PRIMARY KEY ("FACTURA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."FACTURA" ADD CONSTRAINT "UQ_FACTURA_PEDIDO" UNIQUE ("PEDIDO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."FACTURA" ADD CONSTRAINT "UQ_FACTURA_NUMERO" UNIQUE ("NUMERO_FACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."CLIENTE" MODIFY ("CLIENTE_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CLIENTE" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CLIENTE" MODIFY ("DIRECCION_EXACTA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CLIENTE" MODIFY ("CREADO_EN" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CLIENTE" ADD PRIMARY KEY ("CLIENTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."CLIENTE" ADD CONSTRAINT "UQ_CLIENTE_USUARIO" UNIQUE ("USUARIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FERIADO
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."FERIADO" MODIFY ("FERIADO_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FERIADO" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FERIADO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."FERIADO" ADD PRIMARY KEY ("FERIADO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."FERIADO" ADD CONSTRAINT "UQ_FERIADO_FECHA" UNIQUE ("FECHA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CALIFICACION_REPARTIDOR
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" MODIFY ("CALIFICACION_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" MODIFY ("PEDIDO_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" MODIFY ("REPARTIDOR_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" MODIFY ("CLIENTE_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" MODIFY ("PUNTAJE_AMABILIDAD" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" MODIFY ("PUNTAJE_TIEMPO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" MODIFY ("PUNTAJE_PRESENTACION" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" MODIFY ("FECHA_CALIFICACION" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" ADD CONSTRAINT "CK_CALIF_AMA" CHECK (puntaje_amabilidad BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" ADD CONSTRAINT "CK_CALIF_TIEMPO" CHECK (puntaje_tiempo BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" ADD CONSTRAINT "CK_CALIF_PRES" CHECK (puntaje_presentacion BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" ADD PRIMARY KEY ("CALIFICACION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" ADD CONSTRAINT "UQ_CALIF_PEDIDO" UNIQUE ("PEDIDO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."ROL" MODIFY ("ROL_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."ROL" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."ROL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."ROL" ADD CONSTRAINT "CK_ROL_CODIGO" CHECK (codigo IN ('ADMIN', 'CLIENTE', 'REPARTIDOR')) ENABLE;
  ALTER TABLE "CLETAEATS"."ROL" ADD PRIMARY KEY ("ROL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."ROL" ADD CONSTRAINT "UQ_ROL_CODIGO" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AMONESTACION_REPARTIDOR
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."AMONESTACION_REPARTIDOR" MODIFY ("AMONESTACION_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."AMONESTACION_REPARTIDOR" MODIFY ("REPARTIDOR_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."AMONESTACION_REPARTIDOR" MODIFY ("MOTIVO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."AMONESTACION_REPARTIDOR" MODIFY ("FECHA_AMONESTACION" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."AMONESTACION_REPARTIDOR" MODIFY ("ACTIVA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."AMONESTACION_REPARTIDOR" ADD CONSTRAINT "CK_AMON_ACTIVA" CHECK (activa IN ('S', 'N')) ENABLE;
  ALTER TABLE "CLETAEATS"."AMONESTACION_REPARTIDOR" ADD PRIMARY KEY ("AMONESTACION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE_DIRECCION
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" MODIFY ("DIRECCION_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" MODIFY ("CLIENTE_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" MODIFY ("ALIAS" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" MODIFY ("DIRECCION_TEXTO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" MODIFY ("LATITUD" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" MODIFY ("LONGITUD" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" MODIFY ("ES_PREDETERMINADA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" MODIFY ("ACTIVA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" ADD PRIMARY KEY ("DIRECCION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" ADD CONSTRAINT "CK_CLIENTE_DIRECCION_LATITUD" CHECK (latitud BETWEEN -90 AND 90) ENABLE;
  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" ADD CONSTRAINT "CK_CLIENTE_DIRECCION_LONGITUD" CHECK (longitud BETWEEN -180 AND 180) ENABLE;
  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" ADD CONSTRAINT "CK_CLIENTE_DIRECCION_PRED" CHECK (es_predeterminada IN ('S', 'N')) ENABLE;
  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" ADD CONSTRAINT "CK_CLIENTE_DIRECCION_ACTIVA" CHECK (activa IN ('S', 'N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table COMBO
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."COMBO" MODIFY ("COMBO_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."COMBO" MODIFY ("RESTAURANTE_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."COMBO" MODIFY ("NUMERO_COMBO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."COMBO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."COMBO" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."COMBO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."COMBO" MODIFY ("CREADO_EN" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."COMBO" MODIFY ("ACTUALIZADO_EN" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."COMBO" ADD CONSTRAINT "CK_COMBO_NUMERO" CHECK (numero_combo BETWEEN 1 AND 9) ENABLE;
  ALTER TABLE "CLETAEATS"."COMBO" ADD CONSTRAINT "CK_COMBO_ESTADO" CHECK (estado IN ('ACTIVO', 'INACTIVO')) ENABLE;
  ALTER TABLE "CLETAEATS"."COMBO" ADD CONSTRAINT "CK_COMBO_PRECIO_REGLA" CHECK (
        (numero_combo = 1 AND precio = 4000) OR
        (numero_combo = 2 AND precio = 5000) OR
        (numero_combo = 3 AND precio = 6000) OR
        (numero_combo = 4 AND precio = 7000) OR
        (numero_combo = 5 AND precio = 8000) OR
        (numero_combo = 6 AND precio = 9000) OR
        (numero_combo = 7 AND precio = 10000) OR
        (numero_combo = 8 AND precio = 11000) OR
        (numero_combo = 9 AND precio = 12000)
    ) ENABLE;
  ALTER TABLE "CLETAEATS"."COMBO" ADD PRIMARY KEY ("COMBO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."COMBO" ADD CONSTRAINT "UQ_COMBO_NUMERO_POR_REST" UNIQUE ("RESTAURANTE_ID", "NUMERO_COMBO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPARTIDOR
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."REPARTIDOR" MODIFY ("REPARTIDOR_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."REPARTIDOR" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."REPARTIDOR" MODIFY ("DIRECCION_EXACTA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."REPARTIDOR" MODIFY ("DISPONIBILIDAD" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."REPARTIDOR" MODIFY ("KILOMETROS_RECORRIDOS_DIA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."REPARTIDOR" MODIFY ("COSTO_KM_HABIL" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."REPARTIDOR" MODIFY ("COSTO_KM_FERIADO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."REPARTIDOR" MODIFY ("FECHA_INGRESO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."REPARTIDOR" MODIFY ("CREADO_EN" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."REPARTIDOR" ADD CONSTRAINT "CK_REPARTIDOR_DISP" CHECK (disponibilidad IN ('DISPONIBLE', 'OCUPADO', 'INACTIVO')) ENABLE;
  ALTER TABLE "CLETAEATS"."REPARTIDOR" ADD CONSTRAINT "CK_REPARTIDOR_KM" CHECK (kilometros_recorridos_dia >= 0) ENABLE;
  ALTER TABLE "CLETAEATS"."REPARTIDOR" ADD CONSTRAINT "CK_REPARTIDOR_TARIFAS" CHECK (costo_km_habil > 0 AND costo_km_feriado > 0) ENABLE;
  ALTER TABLE "CLETAEATS"."REPARTIDOR" ADD PRIMARY KEY ("REPARTIDOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."REPARTIDOR" ADD CONSTRAINT "UQ_REPARTIDOR_USUARIO" UNIQUE ("USUARIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."USUARIO" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."USUARIO" MODIFY ("ROL_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."USUARIO" MODIFY ("NOMBRE_COMPLETO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."USUARIO" MODIFY ("CEDULA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."USUARIO" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."USUARIO" MODIFY ("TELEFONO_CELULAR" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."USUARIO" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."USUARIO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."USUARIO" MODIFY ("CREADO_EN" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."USUARIO" MODIFY ("ACTUALIZADO_EN" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."USUARIO" ADD CONSTRAINT "CK_USUARIO_ESTADO" CHECK (estado IN ('ACTIVO', 'INACTIVO', 'SUSPENDIDO')) ENABLE;
  ALTER TABLE "CLETAEATS"."USUARIO" ADD PRIMARY KEY ("USUARIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."USUARIO" ADD CONSTRAINT "UQ_USUARIO_CEDULA" UNIQUE ("CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."USUARIO" ADD CONSTRAINT "UQ_USUARIO_CORREO" UNIQUE ("CORREO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PEDIDO
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."PEDIDO" MODIFY ("PEDIDO_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO" MODIFY ("NUMERO_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO" MODIFY ("CLIENTE_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO" MODIFY ("RESTAURANTE_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO" MODIFY ("FECHA_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO" MODIFY ("DIRECCION_ENTREGA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO" MODIFY ("DISTANCIA_KM" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO" MODIFY ("TIPO_TARIFA_DIA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO" MODIFY ("COSTO_KM_APLICADO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO" MODIFY ("CREADO_EN" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO" MODIFY ("ACTUALIZADO_EN" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO" ADD CONSTRAINT "CK_PEDIDO_ESTADO" CHECK (estado IN ('EN_PREPARACION', 'EN_CAMINO', 'SUSPENDIDO', 'ENTREGADO', 'CANCELADO')) ENABLE;
  ALTER TABLE "CLETAEATS"."PEDIDO" ADD CONSTRAINT "CK_PEDIDO_DISTANCIA" CHECK (distancia_km >= 0) ENABLE;
  ALTER TABLE "CLETAEATS"."PEDIDO" ADD CONSTRAINT "CK_PEDIDO_TARIFA_DIA" CHECK (tipo_tarifa_dia IN ('H', 'F')) ENABLE;
  ALTER TABLE "CLETAEATS"."PEDIDO" ADD CONSTRAINT "CK_PEDIDO_COSTO_KM" CHECK (costo_km_aplicado >= 0) ENABLE;
  ALTER TABLE "CLETAEATS"."PEDIDO" ADD PRIMARY KEY ("PEDIDO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLETAEATS"."PEDIDO" ADD CONSTRAINT "UQ_PEDIDO_NUMERO" UNIQUE ("NUMERO_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUEJA_REPARTIDOR
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" MODIFY ("QUEJA_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" MODIFY ("PEDIDO_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" MODIFY ("REPARTIDOR_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" MODIFY ("CLIENTE_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" MODIFY ("CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" MODIFY ("FECHA_QUEJA" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" ADD CONSTRAINT "CK_QUEJA_CATEGORIA" CHECK (categoria IN ('AMABILIDAD', 'TIEMPO', 'PRESENTACION', 'SERVICIO', 'OTRA')) ENABLE;
  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" ADD CONSTRAINT "CK_QUEJA_ESTADO" CHECK (estado IN ('PENDIENTE', 'EN_REVISION', 'RESUELTA', 'RECHAZADA')) ENABLE;
  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" ADD PRIMARY KEY ("QUEJA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PEDIDO_DETALLE
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."PEDIDO_DETALLE" MODIFY ("PEDIDO_DETALLE_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO_DETALLE" MODIFY ("PEDIDO_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO_DETALLE" MODIFY ("COMBO_ID" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO_DETALLE" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO_DETALLE" MODIFY ("PRECIO_UNITARIO" NOT NULL ENABLE);
  ALTER TABLE "CLETAEATS"."PEDIDO_DETALLE" ADD CONSTRAINT "CK_PD_CANTIDAD" CHECK (cantidad > 0) ENABLE;
  ALTER TABLE "CLETAEATS"."PEDIDO_DETALLE" ADD CONSTRAINT "CK_PD_PRECIO" CHECK (precio_unitario > 0) ENABLE;
  ALTER TABLE "CLETAEATS"."PEDIDO_DETALLE" ADD PRIMARY KEY ("PEDIDO_DETALLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AMONESTACION_REPARTIDOR
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."AMONESTACION_REPARTIDOR" ADD CONSTRAINT "FK_AMON_REPARTIDOR" FOREIGN KEY ("REPARTIDOR_ID")
	  REFERENCES "CLETAEATS"."REPARTIDOR" ("REPARTIDOR_ID") ENABLE;
  ALTER TABLE "CLETAEATS"."AMONESTACION_REPARTIDOR" ADD CONSTRAINT "FK_AMON_QUEJA" FOREIGN KEY ("QUEJA_ID")
	  REFERENCES "CLETAEATS"."QUEJA_REPARTIDOR" ("QUEJA_ID") ENABLE;
  ALTER TABLE "CLETAEATS"."AMONESTACION_REPARTIDOR" ADD CONSTRAINT "FK_AMON_ADMIN" FOREIGN KEY ("ADMIN_USUARIO_ID")
	  REFERENCES "CLETAEATS"."USUARIO" ("USUARIO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CALIFICACION_REPARTIDOR
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" ADD CONSTRAINT "FK_CALIF_PEDIDO" FOREIGN KEY ("PEDIDO_ID")
	  REFERENCES "CLETAEATS"."PEDIDO" ("PEDIDO_ID") ENABLE;
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" ADD CONSTRAINT "FK_CALIF_REPARTIDOR" FOREIGN KEY ("REPARTIDOR_ID")
	  REFERENCES "CLETAEATS"."REPARTIDOR" ("REPARTIDOR_ID") ENABLE;
  ALTER TABLE "CLETAEATS"."CALIFICACION_REPARTIDOR" ADD CONSTRAINT "FK_CALIF_CLIENTE" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES "CLETAEATS"."CLIENTE" ("CLIENTE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."CLIENTE" ADD CONSTRAINT "FK_CLIENTE_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "CLETAEATS"."USUARIO" ("USUARIO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE_DIRECCION
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."CLIENTE_DIRECCION" ADD CONSTRAINT "FK_CLIENTE_DIRECCION_CLIENTE" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES "CLETAEATS"."CLIENTE" ("CLIENTE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMBO
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."COMBO" ADD CONSTRAINT "FK_COMBO_RESTAURANTE" FOREIGN KEY ("RESTAURANTE_ID")
	  REFERENCES "CLETAEATS"."RESTAURANTE" ("RESTAURANTE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."FACTURA" ADD CONSTRAINT "FK_FACTURA_PEDIDO" FOREIGN KEY ("PEDIDO_ID")
	  REFERENCES "CLETAEATS"."PEDIDO" ("PEDIDO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDO
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."PEDIDO" ADD CONSTRAINT "FK_PEDIDO_CLIENTE" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES "CLETAEATS"."CLIENTE" ("CLIENTE_ID") ENABLE;
  ALTER TABLE "CLETAEATS"."PEDIDO" ADD CONSTRAINT "FK_PEDIDO_RESTAURANTE" FOREIGN KEY ("RESTAURANTE_ID")
	  REFERENCES "CLETAEATS"."RESTAURANTE" ("RESTAURANTE_ID") ENABLE;
  ALTER TABLE "CLETAEATS"."PEDIDO" ADD CONSTRAINT "FK_PEDIDO_REPARTIDOR" FOREIGN KEY ("REPARTIDOR_ID")
	  REFERENCES "CLETAEATS"."REPARTIDOR" ("REPARTIDOR_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDO_DETALLE
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."PEDIDO_DETALLE" ADD CONSTRAINT "FK_PD_PEDIDO" FOREIGN KEY ("PEDIDO_ID")
	  REFERENCES "CLETAEATS"."PEDIDO" ("PEDIDO_ID") ENABLE;
  ALTER TABLE "CLETAEATS"."PEDIDO_DETALLE" ADD CONSTRAINT "FK_PD_COMBO" FOREIGN KEY ("COMBO_ID")
	  REFERENCES "CLETAEATS"."COMBO" ("COMBO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUEJA_REPARTIDOR
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" ADD CONSTRAINT "FK_QUEJA_PEDIDO" FOREIGN KEY ("PEDIDO_ID")
	  REFERENCES "CLETAEATS"."PEDIDO" ("PEDIDO_ID") ENABLE;
  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" ADD CONSTRAINT "FK_QUEJA_REPARTIDOR" FOREIGN KEY ("REPARTIDOR_ID")
	  REFERENCES "CLETAEATS"."REPARTIDOR" ("REPARTIDOR_ID") ENABLE;
  ALTER TABLE "CLETAEATS"."QUEJA_REPARTIDOR" ADD CONSTRAINT "FK_QUEJA_CLIENTE" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES "CLETAEATS"."CLIENTE" ("CLIENTE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPARTIDOR
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."REPARTIDOR" ADD CONSTRAINT "FK_REPARTIDOR_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "CLETAEATS"."USUARIO" ("USUARIO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "CLETAEATS"."USUARIO" ADD CONSTRAINT "FK_USUARIO_ROL" FOREIGN KEY ("ROL_ID")
	  REFERENCES "CLETAEATS"."ROL" ("ROL_ID") ENABLE;
